POST http://localhost:8080/chat

What is ollama?

###

POST http://localhost:8080/chat-with-stream
Accept: application/stream+json

What is ollama?

###

POST http://localhost:8080/chat-with-parametrized-prompt
Accept: application/stream+json

LLM

###

POST http://localhost:8080/chat-with-roles-and-external-template
Accept: application/stream+json
Content-Type: application/json

{
    "userPromptText": "How to start Spring container?"
}

###

POST http://localhost:8080/chat-with-roles-and-external-template
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "What is a banana?"
}

###

POST http://localhost:8080/chat-extracting-data
Accept: application/json
Content-Type: application/json

{
  "userPromptText": "Extract the key information from the following text delimited by triple backticks and format it in JSON.\n Text : ```Emily Thompson booked a flight on October 10, 2024. She will be flying from New York (JFK) to Los Angeles (LAX) on flight number AA123.The departure time is 8:00 AM, and the arrival time is 11:30 AM. She has a carry-on bag and a checked bag. Her ticket price was $450.00, and she will be seated in 14A.```"
}

####

POST http://localhost:8080/chat-extracting-structured-data
Accept: application/json
Content-Type: application/json

{
  "userPromptText": "Give me information about the best fantasy book"
}

###

POST http://localhost:8080/chat-extracting-structured-data-as-list
Accept: application/json
Content-Type: application/json

{
  "userPromptText": "Give me information about five the best fantasy book"
}

###

POST http://localhost:8080/chat-extracting-structured-data-as-map
Accept: application/json
Content-Type: application/json

{
  "userPromptText": "Give me information about the best fantasy books (title and author)"
}

###

POST http://localhost:8080/chat-with-conversation
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "My name is Luc"
}

###

POST http://localhost:8080/chat-with-conversation
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "What is my name?"
}

###

POST http://localhost:8080/chat-with-advisors
Accept: application/json
Content-Type: application/json

{
  "userPromptText": "What is my name?"
}

###

###

POST http://localhost:8080/chat-with-conversation/id-1
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "My name is Luc"
}

###

POST http://localhost:8080/chat-with-conversation/id-1
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "What is my name?"
}

###

GET http://localhost:8080/get-chat-history/id-1
Accept: application/stream+json
Content-Type: application/json

###

DELETE http://localhost:8080/delete-chat-history/id-1
Accept: application/stream+json
Content-Type: application/json

###

POST http://localhost:8080/chat-with-tools
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "What time is it now?"
}

###

POST http://localhost:8080/chat-with-tools
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "Podaj aktualną godzinę w Warszawie?"
}

###

POST http://localhost:8080/chat-with-tools
Accept: application/stream+json
Content-Type: application/json

{
  "userPromptText": "Calculate 2 to the power od 2"
}

###

POST http://localhost:8080/generate-speech
Content-Type: application/json

{
  "userPromptText": "Spring AI is great"
}

###

POST http://localhost:8080/generate-transcription
Accept: application/json

###

POST http://localhost:8080/generate-audi
Accept: application/json